nameOverride: ""
fullnameOverride: ""

image:
  repository: mack/rakyll-hey
  pullPolicy: IfNotPresent
  tag: "latest"

# global common labels, applied to all resources
commonLabels: {}

podAnnotations: {}
podLabels: {}

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: "50%"
    maxSurge: 0

dnsPolicy: ClusterFirst
terminationGracePeriodSeconds: 30

podSecurityContext:
  runAsNonRoot: false

securityContext:
  privileged: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

tolerations: []
affinity: {}

hey:
  deployment:
    enabled: true
    replicas: 10

    resources:
      requests:
        cpu: 150m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 256Mi

    # Hey params
    targetURL: "http://backend-podinfo:9898"
    timeoutSeconds: 10
    duration: 600s
    # worker count
    concurrency: 10
    # QPS per worker
    qps: 10

  cronjob:
    enabled: false
    schedule: "*/3 * * * *"
    concurrencyPolicy: "Forbid"
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 1
    startingDeadlineSeconds: 20
    suspend: false

    # Job params
    parallelism: 10
    completions: 10
    completionMode: "Indexed"
    activeDeadlineSeconds: 150
    backoffLimit: 0
    ttlSecondsAfterFinished: 900

    resources:
      requests:
        cpu: 150m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 128Mi

    # Hey params
    targetURL: "http://backend-podinfo:9898"
    timeoutSeconds: 10
    duration: 120s
    # worker count
    concurrency: 10
    # QPS per worker
    qps: 10

# Create dummy K8s objects to simulate cluster activity
dummy:
  # Cronjob just sleeps between 0.1 and 3.9 seconds.
  cronjob:
    enabled: true
    schedule: "*/1 * * * *"
    concurrencyPolicy: "Forbid"
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 1
    startingDeadlineSeconds: 20
    suspend: false

    # Job params
    parallelism: 20
    completions: 160
    completionMode: "NonIndexed"
    activeDeadlineSeconds: 120
    backoffLimit: 0
    ttlSecondsAfterFinished: 300

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 10m
        memory: 32Mi
