# Mermin Default Configuration for Local Development
# This configuration file contains default settings for the Mermin eBPF network observability tool for local development.

# Network interfaces to monitor
interface:
  - eth0

# Logging configuration
log_level: debug

# Automatic configuration reloading
auto_reload: false

# API server configuration (health endpoints)
api:
  enabled: true
  listen_address: "0.0.0.0"
  port: 8080

# Metrics server configuration (for Prometheus scraping)
metrics:
  enabled: true
  listen_address: "0.0.0.0"
  port: 10250

# Pipeline configuration
packet_channel_capacity: 1024
packet_worker_count: 2
shutdown_timeout: 5s

# Span/Flow configuration
span:
  max_batch_size: 64
  max_batch_interval: 5s
  max_record_interval: 60s
  generic_timeout: 30s
  icmp_timeout: 10s
  tcp_timeout: 20s
  tcp_fin_timeout: 5s
  tcp_rst_timeout: 5s
  udp_timeout: 60s

# Multiple exporter configuration
exporters:
  - name: "console-debug"
    enabled: true
    exporter_type: "Stdout"
    config:
      Stdout:
        format: "pretty"

  - name: "otlp-production"
    enabled: true
    exporter_type: "Otlp"
    config:
      Otlp:
        endpoint: "http://jaeger:14250"
        timeout_seconds: 5
        protocol: "grpc"
        headers:
          "X-API-Key": "your-api-key"
        batch_size: 100

  - name: "console-compact"
    enabled: true
    exporter_type: "Stdout"
    config:
      Stdout:
        format: "json-compact"
