---
# Long-running HTTP server for testing process name resolution
apiVersion: v1
kind: Pod
metadata:
  name: test-http-server
  namespace: default
  labels:
    app: test-http-server
spec:
  hostPID: true  # Share host PID namespace so PIDs match what eBPF captures
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
---
# Service for the HTTP server
apiVersion: v1
kind: Service
metadata:
  name: test-http-server
  namespace: default
spec:
  selector:
    app: test-http-server
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
---
# Long-running traffic generator
apiVersion: v1
kind: Pod
metadata:
  name: test-traffic-generator
  namespace: default
  labels:
    app: test-traffic-generator
spec:
  hostPID: true  # Share host PID namespace so PIDs match what eBPF captures
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo "Starting persistent traffic generator..."
      echo "Sending requests to test-http-server every 2 seconds"
      while true; do
        curl -s -o /dev/null -w "HTTP %{http_code} at $(date)\n" http://test-http-server/ || true
        sleep 2
      done
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"

