name: Bug Report or Feature Request
description: Report a bug or request a new feature
labels: ["needs-triage"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
        - Feature Request
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Dscription
      description: |
        **Bug:** What went wrong? What did you expect? Include steps to reproduce, logs, error messages.
        **Feature:** What problem are you trying to solve? What's your proposed solution? Include use case, example configuration, similar features in other tools.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version & Environment
      description: "Mermin version, Kubernetes version, platform (e.g., v0.1.0, K8s 1.28, EKS)"
      placeholder: "v0.1.0, Kubernetes 1.28, EKS"

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - eBPF / Flow capture
        - OTLP export
        - Kubernetes metadata
        - Configuration
        - Performance
        - Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
