name: Feature Request
description: Suggest a new feature or enhancement for Mermin
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your use case.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem or limitation are you facing? What use case are you trying to address?
      placeholder: |
        I'm trying to achieve X but currently can't because...
        This would be valuable for Y use case...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Describe the desired behavior and user experience.
      placeholder: |
        I would like to be able to...
        The feature would work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried X but it doesn't work because...
        Another approach could be Y but...

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Category
      description: Which area of Mermin does this feature relate to?
      options:
        - Flow capture / eBPF
        - Protocol support (new protocol parsing)
        - OTLP export / telemetry
        - Kubernetes metadata enrichment
        - Configuration / filtering
        - Performance / optimization
        - Deployment / installation
        - Observability backend integration
        - CLI / tooling
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority / Impact
      description: How important is this feature to your use case?
      options:
        - Critical - Blocking adoption/usage
        - High - Needed for production use
        - Medium - Would significantly improve experience
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: use-case-details
    attributes:
      label: Use Case Details
      description: |
        Provide context about your environment and use case:
        - What's your deployment scenario? (Kubernetes, bare metal, cloud provider)
        - What scale are you operating at? (nodes, pods, flows per second)
        - How would this feature fit into your observability workflow?
      placeholder: |
        We're running Mermin on a 100-node EKS cluster...
        Our backend is Grafana Tempo and we need...
        This would help us achieve...

  - type: textarea
    id: example-config
    attributes:
      label: Example Configuration or API
      description: If you have ideas for how this feature should be configured or used, provide examples
      placeholder: |
        # Example configuration syntax
        feature_name {
          option = "value"
        }
      render: hcl

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other information that would help us understand this feature:
        - Links to similar features in other tools
        - References to standards or specifications
        - Diagrams or mockups
        - Related issues or discussions
      placeholder: Add any other context, screenshots, or links here...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false
        - label: I can help with testing/validation
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've done the following
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been requested
          required: true
        - label: I have reviewed the [documentation](https://github.com/elastiflow/mermin/tree/main/docs) to confirm this feature doesn't already exist
          required: false
