{
 "title": "Mermin Application",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   { "name": "pod_label", "label": "Pod label", "query": "pod" },
   { "name": "query_top_N", "label": "Top N", "query": "3, 5, 10, 25, 50, 100" },
   { "name": "filter", "label": "filter" },
   {
    "name": "ebpf_map",
    "query": {
     "query": "label_values(mermin_ebpf_map_capacity,map)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Flows/Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flows",
   "type": "gauge",
   "description": "Sum of the flows active and flow rate across all Mermin instances",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "flows" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mermin_flow_spans_active_total)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(rate(mermin_flow_spans_created_total[$__rate_interval]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "AVG export latency",
   "type": "stat",
   "description": "Average flow span export latency across all Mermin instances",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(mermin_export_latency_seconds_sum[$__rate_interval]) / rate(mermin_export_latency_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes rate",
   "type": "gauge",
   "description": "Sum of the bytes rate across all Mermin instances",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mermin_interface_bytes_total[$__rate_interval]))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Packets rate",
   "type": "gauge",
   "description": "Sum of the packets rate across all Mermin instances",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mermin_interface_packets_total[$__rate_interval]))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "AVG export batch size",
   "type": "stat",
   "description": "Average count of spans in each OTLP export batch across all Mermin instances",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(mermin_export_batch_size_sum[$__rate_interval]) / rate(mermin_export_batch_size_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flows active (top $query_top_N)",
   "type": "timeseries",
   "description": "Flow spans currently active in Mermin (total and top $query_top_N by pod)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk($query_top_N, sum(mermin_flow_spans_active_total) by ($pod_label))",
     "legendFormat": "{{ $pod_label }}"
    },
    {
     "expr": "sum(mermin_flow_spans_active_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Flows rate (top $query_top_N)",
   "type": "timeseries",
   "description": "Flow spans rate per second created (total and top $query_top_N by pod)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "flows/s" } },
   "targets": [
    {
     "expr": "topk($query_top_N, sum(rate(mermin_flow_spans_created_total[$__rate_interval])) by ($pod_label))",
     "legendFormat": "{{ $pod_label }}"
    },
    {
     "expr": "sum(rate(mermin_flow_spans_created_total[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Export flows export rate (top $query_top_N)",
   "type": "timeseries",
   "description": "Flow span export rate per second (total and top $query_top_N by pod, exporter, status)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "flows/s" } },
   "targets": [
    {
     "expr": "topk($query_top_N, sum(rate(mermin_export_flow_spans_total{status!=\"error\"}[$__rate_interval])) by ($pod_label, exporter, status)) > 0",
     "legendFormat": "{{ $pod_label }}: {{ exporter }}/{{ status }}"
    },
    {
     "expr": "topk($query_top_N, sum(rate(mermin_export_flow_spans_total{status=\"error\"}[$__rate_interval])) by ($pod_label, exporter, status)) * -1 < 0",
     "legendFormat": "{{ $pod_label }}: {{ exporter }}/{{ status }}"
    },
    {
     "expr": "sum(rate(mermin_export_flow_spans_total{status=\"error\"}[$__rate_interval])) by (exporter, status) * -1 < 0",
     "legendFormat": "Total: {{ exporter }}/{{ status }}"
    },
    {
     "expr": "sum(rate(mermin_export_flow_spans_total{status!=\"error\"}[$__rate_interval])) by (exporter, status) > 0",
     "legendFormat": "Total: {{ exporter }}/{{ status }}"
    }
   ]
  },
  {
   "title": "Packets rate processed  (top $query_top_N)",
   "type": "timeseries",
   "description": "Packets per second processed by Mermin (total and top $query_top_N by pod)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk($query_top_N, sum(rate(mermin_interface_packets_total[$__rate_interval])) by ($pod_label))",
     "legendFormat": "{{ $pod_label }}"
    },
    {
     "expr": "sum(rate(mermin_interface_packets_total[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Export latency",
   "type": "heatmap",
   "description": "Breakdown of how fast the K8s informer IP index is updated",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(mermin_export_latency_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Export batch size",
   "type": "heatmap",
   "description": "Breakdown of how fast the K8s informer IP index is updated",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(mermin_export_batch_size_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"ebpf_ringbuf_out\" min, avg, max rate",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min_over_time(sum(rate(mermin_pipeline_duration_seconds_count{stage=\"ebpf_ringbuf_out\"}[$__rate_interval])) by (stage)[$__range:])",
       "legendFormat": "min"
      },
      {
       "expr": "avg_over_time(sum(rate(mermin_pipeline_duration_seconds_count{stage=\"ebpf_ringbuf_out\"}[$__rate_interval])) by (stage)[$__range:])",
       "legendFormat": "avg"
      },
      {
       "expr": "max_over_time(sum(rate(mermin_pipeline_duration_seconds_count{stage=\"ebpf_ringbuf_out\"}[$__rate_interval])) by (stage)[$__range:])",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Mermin pipeline events rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 17, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(mermin_pipeline_duration_seconds_count[$__rate_interval])) by (stage)",
       "legendFormat": "Stage: {{ stage }}"
      }
     ]
    },
    {
     "title": "\"flow_producer_out\" min, avg, max rate",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min_over_time(sum(rate(mermin_pipeline_duration_seconds_count{stage=\"flow_producer_out\"}[$__rate_interval])) by (stage)[$__range:])",
       "legendFormat": "min"
      },
      {
       "expr": "avg_over_time(sum(rate(mermin_pipeline_duration_seconds_count{stage=\"flow_producer_out\"}[$__rate_interval])) by (stage)[$__range:])",
       "legendFormat": "avg"
      },
      {
       "expr": "max_over_time(sum(rate(mermin_pipeline_duration_seconds_count{stage=\"flow_producer_out\"}[$__rate_interval])) by (stage)[$__range:])",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "\"k8s_decorator_out\" min, avg, max rate",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min_over_time(sum(rate(mermin_pipeline_duration_seconds_count{stage=\"k8s_decorator_out\"}[$__rate_interval])) by (stage)[$__range:])",
       "legendFormat": "min"
      },
      {
       "expr": "avg_over_time(sum(rate(mermin_pipeline_duration_seconds_count{stage=\"k8s_decorator_out\"}[$__rate_interval])) by (stage)[$__range:])",
       "legendFormat": "avg"
      },
      {
       "expr": "max_over_time(sum(rate(mermin_pipeline_duration_seconds_count{stage=\"k8s_decorator_out\"}[$__rate_interval])) by (stage)[$__range:])",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "\"ebpf_ringbuf_out\" duration ",
     "type": "heatmap",
     "description": "Mermin \"ebpf_ringbuf_out\" pipeline stage duration ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(mermin_pipeline_duration_seconds_bucket{stage=\"ebpf_ringbuf_out\"}[$__rate_interval])) by (stage, le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "\"flow_producer_out\" duration ",
     "type": "heatmap",
     "description": "Mermin \"flow_producer_out\" pipeline stage duration ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(mermin_pipeline_duration_seconds_bucket{stage=\"flow_producer_out\"}[$__rate_interval])) by (stage, le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "\"k8s_decorator_out\" duration ",
     "type": "heatmap",
     "description": "Mermin \"k8s_decorator_out\" pipeline stage duration ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(mermin_pipeline_duration_seconds_bucket{stage=\"k8s_decorator_out\"}[$__rate_interval])) by (stage, le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "K8s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8s decoration rate (top $query_top_N) ",
     "type": "timeseries",
     "description": "Flow spans per second decorated by the K8s decorator (total and top $query_top_N by pod)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "spans/s" } },
     "targets": [
      {
       "expr": "topk($query_top_N, sum(rate(mermin_k8s_decorator_flow_spans_total[$__rate_interval])) by ($pod_label, status))",
       "legendFormat": "{{ $pod_label }}: {{ status }}"
      },
      {
       "expr": "sum(rate(mermin_k8s_decorator_flow_spans_total[$__rate_interval])) by (status)",
       "legendFormat": "Total: {{ status }}"
      }
     ]
    },
    {
     "title": "K8s informer index upate rate (top $query_top_N)",
     "type": "timeseries",
     "description": "K8s informer index upate rate (total and top $query_top_N by pod)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($query_top_N, sum(rate(mermin_k8s_watcher_ip_index_update_duration_seconds_count[$__rate_interval])) by ($pod_label))",
       "legendFormat": "{{ $pod_label }}"
      },
      {
       "expr": "sum(rate(mermin_k8s_watcher_ip_index_update_duration_seconds_count[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "K8s watcher events rate (top $query_top_N)",
     "type": "timeseries",
     "description": "K8s watcher events rate by event type (total and top $query_top_N by pod, event_type)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "topk($query_top_N, sum(rate(mermin_k8s_watcher_events_total[$__rate_interval])) by ($pod_label, event, kind)) > 0",
       "legendFormat": "{{ $pod_label }}: {{ event }}/{{ kind }}"
      },
      {
       "expr": "sum(rate(mermin_k8s_watcher_events_total[$__rate_interval])) by (event, kind) > 0",
       "legendFormat": "Total: {{ event }}/{{ kind }}"
      }
     ]
    },
    {
     "title": "K8s informer index upate duration ",
     "type": "heatmap",
     "description": "Breakdown of how fast the K8s informer IP index is updated",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "sum(rate(mermin_k8s_watcher_ip_index_update_duration_seconds_bucket[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SYS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "/sys/fs/bpf writable (top $query_top_N false)",
     "type": "stat",
     "description": "Shows pods only when `/sys/fs/bpf` is not writable (top $query_top_N false)",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 855 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bottomk($query_top_N, sum(mermin_ebpf_bpf_fs_writable) by ($pod_label))",
       "legendFormat": "{{ $pod_label }} /sys/fs/bpf writable"
      }
     ]
    },
    {
     "title": "eBPF attachment method",
     "type": "stat",
     "description": "eBPF attachment method (TC or TCX)",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 855 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mermin_ebpf_method) by ($pod_label, attachment) > 0",
       "legendFormat": "{{ $pod_label }}"
      }
     ]
    },
    {
     "title": "Bytes processed rate (top $query_top_N)",
     "type": "timeseries",
     "description": "Total number of bytes processed by Mermin (top $query_top_N by pod)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 858 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk($query_top_N, sum(rate(mermin_interface_bytes_total[$__rate_interval])) by ($pod_label))",
       "legendFormat": "{{ $pod_label }}"
      }
     ]
    },
    {
     "title": "Packets processed (top $query_top_N)",
     "type": "timeseries",
     "description": "Total number of packets processed by Mermin (top $query_top_N)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 858 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk($query_top_N, sum(rate(mermin_interface_packets_total[$__rate_interval])) by ($pod_label))",
       "legendFormat": "{{ $pod_label }}"
      }
     ]
    },
    {
     "title": "TaskManager tasks active (top $query_top_N)",
     "type": "timeseries",
     "description": "Current active Mermin TaskManager tasks (top $query_top_N by pod)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 863 },
     "fieldConfig": { "defaults": { "unit": "tasks" } },
     "targets": [
      {
       "expr": "topk($query_top_N ,sum(mermin_taskmanager_tasks_active) by ($pod_label, task))",
       "legendFormat": "Active: {{ $pod_label }}/{{ task }}"
      }
     ]
    },
    {
     "title": "Channels used % (top $query_top_N)",
     "type": "timeseries",
     "description": "Ratio of used channel capacity (top $query_top_N by pod, channel)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 863 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk($query_top_N, sum(mermin_channel_entries / mermin_channel_capacity) by ($pod_label, channel))",
       "legendFormat": "{{ $pod_label }}: {{ channel }}"
      }
     ]
    },
    {
     "title": "eBPF maps capacity used % (max)",
     "type": "timeseries",
     "description": "Ratio of used eBPF map capacity (max)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 872 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(mermin_ebpf_map_entries / mermin_ebpf_map_capacity) by (map)",
       "legendFormat": "{{ map }}"
      }
     ]
    },
    {
     "title": "eBPF maps ops rate",
     "type": "timeseries",
     "description": "Total rate of the eBPF map operations (by map, operation, status)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 872 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mermin_ebpf_map_ops_total{status=\"ok\"}[$__rate_interval])) by (map, operation, status)",
       "legendFormat": "Total: {{ map }}/{{ operation }}/{{ status }}"
      },
      {
       "expr": "sum(rate(mermin_ebpf_map_ops_total{status=\"not_found\"}[$__rate_interval])) by (map, operation, status)",
       "legendFormat": "Total: {{ map }}/{{ operation }}/{{ status }}"
      },
      {
       "expr": "sum(rate(mermin_ebpf_map_ops_total{status=\"error\"}[$__rate_interval])) by (map, operation, status) * -1",
       "legendFormat": "Total: {{ map }}/{{ operation }}/{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "SYS: eBPF map $ebpf_map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "ebpf_map",
   "collapsed": true,
   "panels": [
    {
     "title": "eBPF map capacity used % (top $query_top_N)",
     "type": "timeseries",
     "description": "Ratio of used eBPF map capacity (top $query_top_N by pod, map)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk($query_top_N, sum(mermin_ebpf_map_entries{map=~\"$ebpf_map\"} / mermin_ebpf_map_capacity{map=~\"$ebpf_map\"}) by ($pod_label, map))",
       "legendFormat": "{{ $pod_label }}: {{ map }}"
      }
     ]
    },
    {
     "title": "eBPF map ops (top $query_top_N)",
     "type": "timeseries",
     "description": "Rate of the eBPF map operations (top $query_top_N by pod, map, operation, status)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk($query_top_N ,sum(rate(mermin_ebpf_map_ops_total{map=\"$ebpf_map\", status=\"ok\"}[$__rate_interval])) by ($pod_label, map, operation, status))",
       "legendFormat": "{{ $pod_label }}: {{ map }}/{{ operation }}/{{ status }}"
      },
      {
       "expr": "topk($query_top_N ,sum(rate(mermin_ebpf_map_ops_total{map=\"$ebpf_map\", status=\"not_found\"}[$__rate_interval])) by ($pod_label, map, operation, status))",
       "legendFormat": "{{ $pod_label }}: {{ map }}/{{ operation }}/{{ status }}"
      },
      {
       "expr": "topk($query_top_N ,sum(rate(mermin_ebpf_map_ops_total{map=\"$ebpf_map\", status=\"error\"}[$__rate_interval])) by ($pod_label, map, operation, status)) * -1",
       "legendFormat": "{{ $pod_label }}: {{ operation }}/{{ status }}"
      }
     ]
    },
    {
     "title": "eBPF map bytes (top $query_top_N)",
     "type": "timeseries",
     "description": "Rate of the eBPF map bytes processed (top $query_top_N by pod)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 382 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($query_top_N ,sum(rate(mermin_ebpf_map_bytes_total{map=\"$ebpf_map\"}[$__rate_interval])) by ($pod_label, map))",
       "legendFormat": "{{ $pod_label }}: {{ map }}"
      }
     ]
    }
   ]
  }
 ]
}