# Option 2: Database in Separate Namespace
# Deploys PostgreSQL in isolated databases namespace
# Best for: Realistic architecture demos, database traffic analysis

---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    tier: data
    environment: shared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: databases
  labels:
    app: postgres
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: testdb
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: databases
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  type: ClusterIP
---
# Database client pod in demo-app namespace that queries the database
apiVersion: v1
kind: Pod
metadata:
  name: db-query-client
  namespace: demo-app
  labels:
    app: db-client
    tier: client
spec:
  containers:
  - name: psql
    image: postgres:15
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting database query client..."
        echo "Target: postgres.databases.svc.cluster.local:5432"
        echo ""
        
        # Wait for database to be ready
        until PGPASSWORD=password psql -h postgres.databases.svc.cluster.local -U postgres -d testdb -c "SELECT 1" > /dev/null 2>&1; do
          echo "[$(date +%H:%M:%S)] Waiting for database to be ready..."
          sleep 2
        done
        
        echo "[$(date +%H:%M:%S)] Database is ready!"
        echo ""
        
        # Continuous query loop
        while true; do
          echo "[$(date +%H:%M:%S)] Querying database in databases namespace..."
          
          RESULT=$(PGPASSWORD=password psql -h postgres.databases.svc.cluster.local -U postgres -d testdb -t -c "SELECT COUNT(*) FROM pg_database" 2>&1)
          
          if [ $? -eq 0 ]; then
            echo "[$(date +%H:%M:%S)] ✓ Query successful - Found $RESULT databases"
          else
            echo "[$(date +%H:%M:%S)] ✗ Query failed: $RESULT"
          fi
          
          echo "[$(date +%H:%M:%S)] Sleeping 10 seconds..."
          echo ""
          sleep 10
        done
    env:
    - name: PGPASSWORD
      value: password
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi

